###
POST http://localhost:8080/api/mail/
Authorization: Bearer secret.jwt.token
content-type: application/json

{
    "to": "federicozacahotmail.com",
    "subject": "Information",
    "message": "A new message has been created"
}
